name: pack

on:
  push:
    branches:
      - v5.2.1

jobs:
  publish:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.7'

    - name: Install main
      shell: bash -l {0}
      run: |
        pip install .

    - name: Run pyinstaller
      shell: bash -l {0}
      run: |
        pip install pyinstaller
        pyinstaller labelme.spec

    # 生成并上传
    - name: Upload macOS & Linux
      uses: actions/upload-artifact@v2
      with:
        path: ./dist/labelme
        name: labelme-${{ runner.os }}-5.2.1
        content_type: application/octet-stream
      if: runner.os != 'Windows'

    # 生成并上传
    - name: Upload Windows
      uses: actions/upload-artifact@v2
      with:
        path: ./dist/labelme.exe
        name: Labelme-5.2.1.exe
        content_type: application/octet-stream
      if: runner.os == 'Windows'

    # 生成并上传
    - name: Create dmg for macOS
      run: |
        npm install -g create-dmg
        cd dist
        create-dmg Labelme.app || test -f Labelme\ 0.0.0.dmg
        mv Labelme\ 0.0.0.dmg Labelme.dmg
      if: runner.os == 'macOS'

    - name: Upload  macOS
      uses: actions/upload-artifact@v2
      with:
        name: Labelme-5.2.1.dmg
        content_type: application/octet-stream
        path: ./dist/Labelme.dmg
      if: runner.os == 'macOS'
